### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tomoyk** [cdsl-research/ecoman#21]
- [ ] Display ESXi Node's Health
- [ ] Log with timestamp
- [ ] Display the last crawled time
- [ ] Display ESXi Node Resources(RAM, CPU, Storage)
- [x] VM Numbering over ESXi Nodes
- [x] VM Status Summary (e.g. Power ON 21, Power OFF 14)
- [ ] VM List CSV Download

**Comment by tomoyk** [comment]
esxi commands ref:

https://www.nakivo.com/blog/most-useful-esxcli-esxi-shell-commands-vmware-environment/
